[build]
  command = "python manage.py collectstatic --noinput && python manage.py migrate"
  publish = "staticfiles"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[context.production.environment]
  DJANGO_SETTINGS_MODULE = "myproject.settings"
  DEBUG = "False"
  SECRET_KEY = "your-production-secret-key"

[context.deploy-preview.environment]
  DJANGO_SETTINGS_MODULE = "myproject.settings"
  DEBUG = "True"
